### PR TITLE
Core: Fixes deprecated calls to jQuery trim. Fixes #2327

### LINKED ISSUE #2327: $.trim deprecated in jQuery 3.5.0
# Subject of the issue
jQuery 3.5.0 has depreacted `$.trim` and should use `String.prototype.trim` instead

### Your environment
* version of `jquery-validate`: 1.19.1
* which browser and its version: N/A

### Steps to reproduce
See [jQuery 3.5.0 release notes](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)

### PR DESCRIPTION
**Pull request by brighton1101**
This fixes the issue with deprecation and adds the polyfill for `String.prototype.trim` for browser support.

### CODE REVIEW

File: src/core.js [hunk 1]
```diff
@@ -1,3 +1,12 @@
+// JQuery trim is deprecated, polyfill native js method if not defined
+if ( !String.prototype.trim ) {
```
Comment (staabm) [inline src/core.js:2]: We should not pollute the prototype of builtin objects. Please instead create a local trim-function instead

Comment (brighton1101) [reply src/core.js]: Fixed.

File: src/core.js [hunk 2]
```diff
@@ -1,3 +1,10 @@
+// JQuery trim is deprecated, provide a trim method based on String.prototype.trim
+function trim( str ) {
```
Comment (staabm) [inline src/core.js:2]: Please move the function into a local variable and move it down to the functions where it is used

Comment (brighton1101) [reply src/core.js]: Done.

**Comment by brighton1101** [comment]
@staabm @Arkni Any updates? We need to update to JQuery 3.5.1 and depend on this change being made

**Comment by staabm** [comment]
@Arkni could you take care of merging this and tagging a new release?

**Comment by Arkni** [comment]
@staabm, I will try my best doing it this night or tomorrow.

**Comment by Arkni** [comment]
@staabm

My machine is behaving strangely and I couldn't run `jquery-release` for some reason. It may take me some time to investigate the issue and create a release. Could you please take over the task?

Thank you and sorry for the inconvenience.

**Comment by staabm** [comment]
trying to do a release now

**Comment by Arkni** [comment]
Thanks a lot @staabm for the release :)

(And sorry for not being active. I'm still in a long pause from a lot of things including open source. It may take me a few more months to be able to help triaging issues or review PRs the way I used to.)

**Comment by staabm** [comment]
@Arkni no worries. Take your time - there are a lot of things which are more important then this project

**Comment by bytestream** [comment]
This doesn't resolve all deprecations. Will send another PR

**Comment by bytestream** [comment]
Created https://github.com/jquery-validation/jquery-validation/pull/2335

**Comment by Tandulje** [comment]
Hi...i'am using jquery -v3.5.1 and jquery.validate -v1.9.2

My code is 
var settings = $('form').validate().settings;
settings.rules['UserPrincipalName'].required = true;

it gives error
**VM155:294 Uncaught TypeError: Cannot set property 'required' of undefined**

When i was on older version jquey -v2.1.4 that it is working fine **_but now not working with jquey- v3.5.1_**

Please give some solution on it.
I go through lots of link but not getting related to this.
Please let me know how can i fix this issue.

**Comment by bytestream** [comment]
@Tandulje please open a new issue, this is nothing to do with this PR
